### 关于Numpy的练习题

这是一些常见的Numpy功能的实现练习

**提交要求**：
- 必须用Jupyter Notebook完成，保存为ipynb格式提交
- 提交文件名为“Python数据分析第2次作业+班级+姓名.ipynb” （注：请规范文件名）
- 提交到刘顿同学的邮箱 810792334@qq.com
- 提交的截止时间为2019年3月1日下午17:00

<hr>

（1）如何查找数组的内存大小

In [1]:
import numpy as np
import sys

a=np.array([1,2,3,4,5])
print("a的内存大小为:",a.size*a.itemsize)

a的内存大小为: 20


<hr>

(2) 创建大小为10的空向量，但第五个值为1

In [2]:
vec=np.zeros(9)
vec[4]=1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0.]


<hr>

(3) 创建一个3x3矩阵，其值范围为0到8

In [3]:
a1= np.arange(9).reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<hr>

(4)  创建一个2d数组，边框为1，内部为0

In [4]:
def create(n):
    arr=np.zeros([n]*2)
    arr[[0,-1],:]=1
    arr[:,[0,-1]]=1
    return arr

a2=create(10)
print(a2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


<hr>

(5) 考虑一个（6,7,8）形状数组，第100个元素的索引（x，y，z）是什么？

In [5]:
print("第100个元素的索引是:",np.unravel_index(100,(6,7,8)))

第100个元素的索引是: (1, 5, 4)


<hr>

(6) 将5x3矩阵乘以3x2矩阵（实矩阵乘积）

In [6]:
a3=np.ones((5,3))@np.ones((3,2))
print(a3)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


<hr>

(7) 如何获得与2020年3月相对应的所有日期？

In [7]:
a4=np.arange('2020-03', '2020-04', dtype='datetime64[D]')
print(a4)

['2020-03-01' '2020-03-02' '2020-03-03' '2020-03-04' '2020-03-05'
 '2020-03-06' '2020-03-07' '2020-03-08' '2020-03-09' '2020-03-10'
 '2020-03-11' '2020-03-12' '2020-03-13' '2020-03-14' '2020-03-15'
 '2020-03-16' '2020-03-17' '2020-03-18' '2020-03-19' '2020-03-20'
 '2020-03-21' '2020-03-22' '2020-03-23' '2020-03-24' '2020-03-25'
 '2020-03-26' '2020-03-27' '2020-03-28' '2020-03-29' '2020-03-30'
 '2020-03-31']


<hr>

(8) 创建一个大小为10的向量，其值范围为0到1；但是0和1都被排除

In [8]:
a5=np.linspace(0,1,11,endpoint=False)[1:]
print(a5)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


 <hr>

(9) 减去矩阵每行的平均值，输出新的矩阵

In [9]:
a6=np.random.rand(4,5)
print("原数组为:\n",a6)
a6=a6-a6.mean(axis=1,keepdims=True)
print("每行减去平均值后的数组为:\n",a6)

原数组为:
 [[0.98825988 0.7626228  0.3053863  0.89607823 0.01115976]
 [0.26048467 0.09134349 0.05031374 0.95174256 0.47533494]
 [0.49406093 0.6752283  0.38296134 0.88263576 0.02814603]
 [0.15051007 0.62277038 0.82584179 0.34035085 0.18188635]]
每行减去平均值后的数组为:
 [[ 0.39555848  0.16992141 -0.28731509  0.30337684 -0.58154164]
 [-0.1053592  -0.27450039 -0.31553014  0.58589868  0.10949106]
 [ 0.00145446  0.18262182 -0.10964513  0.39002929 -0.46446044]
 [-0.27376182  0.19849849  0.4015699  -0.08392104 -0.24238554]]


 <hr>

(10) 考虑四维数组，如何一次得到最后两个轴的总和？

In [10]:
a7=np.random.randint(0,10,(4,5,6,7))
print(a7)
final_sum=a7.sum(axis=(-2,-1))
print("最后两个轴的总和为:",final_sum)

[[[[9 2 2 5 1 8 7]
   [8 0 4 6 4 8 6]
   [1 0 8 7 7 8 6]
   [1 1 0 2 3 3 2]
   [6 4 9 7 6 3 4]
   [8 7 4 8 9 0 5]]

  [[6 5 5 7 3 4 0]
   [4 0 3 5 0 2 0]
   [2 9 9 9 7 6 8]
   [4 1 3 4 1 6 8]
   [4 7 7 8 7 1 1]
   [9 3 8 9 0 3 8]]

  [[9 0 5 6 1 8 1]
   [4 3 3 2 4 4 4]
   [3 1 7 1 5 0 1]
   [8 6 0 0 0 5 3]
   [8 8 1 3 3 4 7]
   [6 4 8 6 9 1 2]]

  [[4 6 5 1 3 4 7]
   [7 9 0 4 3 2 9]
   [8 0 9 7 0 2 6]
   [2 9 7 3 9 6 9]
   [4 0 3 0 0 8 8]
   [0 3 0 5 5 4 4]]

  [[1 4 9 9 1 9 9]
   [1 8 6 2 8 0 7]
   [7 3 9 0 7 2 2]
   [2 8 7 9 2 7 6]
   [7 6 7 3 1 1 1]
   [7 0 5 8 5 8 5]]]


 [[[4 0 7 0 1 1 8]
   [2 6 8 2 0 9 6]
   [1 6 8 8 8 6 5]
   [5 6 9 5 3 9 9]
   [3 7 8 1 9 0 2]
   [2 6 3 2 9 8 8]]

  [[4 4 9 5 1 2 4]
   [9 1 1 3 6 1 0]
   [7 9 6 9 0 2 5]
   [5 5 5 8 6 2 5]
   [5 2 5 5 4 9 4]
   [6 9 4 2 0 4 8]]

  [[9 6 2 9 8 8 7]
   [0 5 9 9 1 1 6]
   [4 8 4 7 1 2 9]
   [5 0 6 8 1 8 8]
   [5 3 9 1 1 7 2]
   [0 9 8 3 1 1 5]]

  [[8 7 8 5 1 6 7]
   [3 3 6 4 0 8 3]
   [7 7 3 0 2 2 1]
   [5 6 7 2 7

 <hr>

(11) 考虑一个数组 Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], 如何生成一个数组 R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

In [11]:
help(np.lib.stride_tricks.as_strided)

Help on function as_strided in module numpy.lib.stride_tricks:

as_strided(x, shape=None, strides=None, subok=False, writeable=True)
    Create a view into the array with the given shape and strides.
    
    .. warning:: This function has to be used with extreme care, see notes.
    
    Parameters
    ----------
    x : ndarray
        Array to create a new.
    shape : sequence of int, optional
        The shape of the new array. Defaults to ``x.shape``.
    strides : sequence of int, optional
        The strides of the new array. Defaults to ``x.strides``.
    subok : bool, optional
        .. versionadded:: 1.10
    
        If True, subclasses are preserved.
    writeable : bool, optional
        .. versionadded:: 1.12
    
        If set to False, the returned array will always be readonly.
        Otherwise it will be writable if the original array was. It
        is advisable to set this to False if possible (see Notes).
    
    Returns
    -------
    view : ndarray
    
   

<a href="https://www.jb51.cc/python/185910.html"><img src="https://www.jb51.cc/images/logo.jpg">
    
**点击图片去看用法**

In [12]:
Z=np.arange(1,15)
R=np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


 <hr>

(12) 如何在长度为100的随机数组中找到最常见的值？

In [13]:
a8=np.random.randint(0,5,100)
print(a8)
print("最常见的值为:",np.bincount(a8).argmax())

[4 4 0 1 4 0 1 4 1 2 1 4 0 1 3 0 0 1 2 3 4 3 1 4 2 1 0 1 3 3 3 1 2 3 2 4 1
 1 3 1 2 3 0 0 4 0 2 2 3 2 0 2 1 0 4 4 0 4 1 2 0 0 4 0 2 0 3 4 4 1 4 3 2 4
 1 1 0 4 4 0 0 2 2 1 3 2 3 2 4 3 1 3 3 0 4 2 4 2 4 0]
最常见的值为: 4


 <hr>

(13) 如何获取长度为100的随机数组中的前n个最大值

<a href="https://blog.csdn.net/MacwinWin/article/details/80002584">
点击查看np.argpartition的使用

In [14]:
a9=np.random.randint(0,1000,100,dtype=int)
print(np.sort(a9)[::-1])
n=int(input("请输入想找到前多少个最大值:"))
print(f"前{n}个最大值为:",a9[np.argpartition(a9,-n)[-n:]])

[988 980 967 953 928 925 924 901 857 853 840 832 824 821 820 809 807 792
 756 754 722 711 699 693 689 684 671 666 657 651 647 645 632 631 585 584
 584 565 551 547 537 522 508 500 497 485 468 435 429 428 420 415 413 401
 396 396 369 357 355 330 321 316 303 293 290 288 284 270 262 258 253 237
 233 223 223 213 201 195 168 165 159 148 142 120 120 115 110 106 102  94
  91  75  73  68  54  47  43  32  24  15]


请输入想找到前多少个最大值: 5


前5个最大值为: [928 953 967 980 988]


<hr>

#### 有兴趣的同学，欢迎继续挑战本次练习的完整题库

[ref] https://github.com/rougier/numpy-100